name: CI for Krypton Files Service
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build & test the FS docker image
      run: make ci_test

    - name: Cleanup
      if: always()
      run: make clean && docker logout
